### PR TITLE
Code split and refactor

### PR DESCRIPTION
**Pull request by impliedchaos**
Hi!  I made several changes over the last week:

- Updated to only use Youtube-DL to decode the url's signature to improve speed (Youtube-DL has a lot of overhead).  This also means direct access to premium stuff without having to setup authentication for YDL as well.
- Added stream quality preferences.
- Added scrobbling to YouTube Music so that play history would be updated.
- Split code into individual source files per class. `library.py` is still huge.
- Added auto playlists / mood & genre playlists / subscriptions to Library Browser.
- Added options for more stuff.
- Used `mopidy-gmusic` code to handle timer events, and proper scrobbling.
- Added support for unauthenticated access to YouTube Music.

Thanks!

### CODE REVIEW

**Comment by impliedchaos** [comment]
Other changes I forgot to list before:
- changed "ytm" uri scheme name to "ytmusic" for better legibility
- also changed uris from HTTP GET style to just colon separated to be more like mopidy-gmusic and so it would interact with existing frontends easier
- used dephell to generate setup.py from pyproject.toml just so github could parse dependencies and for people who want to build the old fashioned way (honestly, poetry is so much easier and better)

**Comment by Ham5andw1ch** [comment]
This is pretty insane. I'll probably clone the branch later and see how it performs, but it looks really cool just from the way you described it. Did you implement any of the searching functionality in the process? At the moment, that doesn't seem to be functional in the main branch.

**Comment by impliedchaos** [comment]
> Did you implement any of the searching functionality in the process? At the moment, that doesn't seem to be functional in the main branch.

Searching works for me. I didn't change too much there except to return artists, albums, and tracks instead of just tracks, and to try to lower the number of ytmusicapi calls to speed things up.

**Comment by stuartf** [comment]
This is awesome, and search is working for me as well.

**Pull request merged**
